# Generated by Django 5.2 on 2025-04-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
                ('documento', models.BigIntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.BigIntegerField()),
                ('celular', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('documento', models.BigIntegerField()),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('peso', models.IntegerField()),
                ('esterilizacion', models.BooleanField()),
                ('reactivo', models.BooleanField()),
                ('vacunas', models.BooleanField()),
                ('alergias', models.CharField(max_length=55)),
                ('tipo_alergias', models.CharField(blank=True, max_length=55, null=True)),
                ('tipo_medicamento', models.CharField(max_length=55)),
                ('tipo_alimentos', models.CharField(max_length=55)),
                ('veces_alimento', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('hora', models.TimeField()),
                ('planes', models.CharField(choices=[('0-5 kg', '0-5 kg'), ('5-15 kg', '5-15 kg'), ('15-25 kg', '15-25 kg'), ('25-35 kg', '25-35 kg'), ('Mas de 35 kg', 'Mas de 35 kg')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuarios.cliente')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='usuarios.empleado')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuarios.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('documento', models.BigIntegerField()),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.checkin')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='usuarios.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='usuarios.reserva'),
        ),
    ]
